#!/usr/bin/env bash

if [ $# -gt 0 ]; then

    if [ "$1" == "init" ]; then
        shift 1
        docker-compose run --rm openvpn ovpn_genconfig -u udp://$@
        docker-compose run --rm openvpn ovpn_initpki

    elif [ "$1" == "start" ]; then
        docker-compose up -d openvpn

    elif [ "$1" == "stop" ]; then
        docker-compose down

    elif [ "$1" == "add" ]; then
        shift 1
        docker-compose run --rm openvpn easyrsa build-client-full $@
        docker-compose run --rm openvpn ovpn_getclient $@ > clients/$@.ovpn

    elif [ "$1" == "remove" ]; then
        shift 1
        docker-compose run --rm openvpn ovpn_revokeclient $@ remove

else
    docker-compose ps
fi